CREATE TABLE BTC_USER.BLOCK_HEADERS
(
    BLOCK_HEADER_REF NUMBER       NOT NULL,
    WRITE_TIMESTAMP  TIMESTAMP(6) NOT NULL,
    VERSION          NUMBER(10,0) NOT NULL,
    PREV_HASH        VARCHAR2(64) NOT NULL,
    MERKLE_TREE_ROOT VARCHAR2(64) NOT NULL,
    TIME             TIMESTAMP(6) NOT NULL,
    BITS             NUMBER(10,0) NOT NULL,
    NONCE            NUMBER(10,0) NOT NULL,
    TX_COUNT         NUMBER(5,0)  NOT NULL,
    BLOCK_HASH       VARCHAR2(64)     NULL,
    BLOCK_HEIGHT     NUMBER(10,0)     NULL,
    BLOCK_INDEX      NUMBER           NULL,
    FEE              NUMBER           NULL,
    RECLAIMED_FEE    NUMBER           NULL
)
ORGANIZATION HEAP
TABLESPACE USERS
LOGGING
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
NOROWDEPENDENCIES
/
ALTER TABLE BTC_USER.BLOCK_HEADERS
    ADD CONSTRAINT BLOCK_HEADERS_PK
    PRIMARY KEY (BLOCK_HEADER_REF)
    USING INDEX TABLESPACE USERS
                PCTFREE 10
                INITRANS 2
                MAXTRANS 255
                STORAGE(BUFFER_POOL DEFAULT)
    LOGGING
    ENABLE
    VALIDATE
/
ALTER TABLE BTC_USER.BLOCK_TRANSACTIONS
    ADD CONSTRAINT BLOCK_TRANSACTION_FK1
    FOREIGN KEY (BLOCK_HEADER_REF)
    REFERENCES BTC_USER.BLOCK_HEADERS (BLOCK_HEADER_REF)
    ON DELETE CASCADE
    ENABLE
    VALIDATE
/
