DROP INDEX BTC_USER.BLOCK_TRANSACTIONS_INDX2
/
CREATE BITMAP INDEX BTC_USER.BLOCK_TRANSACTIONS_INDX2
    ON BTC_USER.BLOCK_TRANSACTIONS(TX_COINBASE_FLAG)
TABLESPACE USERS
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(INITIAL 64K
        BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
/
