DROP INDEX BTC_USER.BLOCK_TRANSACTIONS_INDX1
/
CREATE INDEX BTC_USER.BLOCK_TRANSACTIONS_INDX1
    ON BTC_USER.BLOCK_TRANSACTIONS(BLOCK_HEADER_REF)
TABLESPACE USERS
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(INITIAL 64K
        BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
/
