CREATE TABLE BTC_USER.BLOCK_TRANSACTIONS
(
    BLOCK_TRANSACTION_REF NUMBER       NOT NULL,
    BLOCK_HEADER_REF      NUMBER       NOT NULL,
    TX_HASH               VARCHAR2(64) NOT NULL,
    TX_VERSION            NUMBER       NOT NULL,
    TX_IN_COUNT           NUMBER(8,0)  NOT NULL,
    TX_OUT_COUNT          NUMBER(8,0)  NOT NULL,
    TX_LOCK_TIME          NUMBER       NOT NULL,
    TX_LOCK_TIMESTAMP     TIMESTAMP(6)     NULL,
    TX_COINBASE_FLAG      CHAR(1)      NOT NULL,
    FEE                   NUMBER           NULL
)
ORGANIZATION HEAP
TABLESPACE USERS
LOGGING
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
NOROWDEPENDENCIES
/
ALTER TABLE BTC_USER.BLOCK_TRANSACTIONS
    ADD CONSTRAINT BLOCK_TRANSACTIONS_PK
    PRIMARY KEY (BLOCK_TRANSACTION_REF)
    USING INDEX TABLESPACE USERS
                PCTFREE 10
                INITRANS 2
                MAXTRANS 255
                STORAGE(BUFFER_POOL DEFAULT)
    LOGGING
    ENABLE
    VALIDATE
/
ALTER TABLE BTC_USER.TRANSACTION_OUTPUTS
    ADD CONSTRAINT TRANSACTION_OUTPUT_FK1
    FOREIGN KEY (BLOCK_TRANSACTION_REF)
    REFERENCES BTC_USER.BLOCK_TRANSACTIONS (BLOCK_TRANSACTION_REF)
    ON DELETE CASCADE
    ENABLE
    VALIDATE
/
ALTER TABLE BTC_USER.TRANSACTION_INPUTS
    ADD CONSTRAINT TRANSACTION_INPUT_FK1
    FOREIGN KEY (BLOCK_TRANSACTION_REF)
    REFERENCES BTC_USER.BLOCK_TRANSACTIONS (BLOCK_TRANSACTION_REF)
    ON DELETE CASCADE
    ENABLE
    VALIDATE
/
ALTER TABLE BTC_USER.BLOCK_TRANSACTIONS
    ADD CONSTRAINT BLOCK_TRANSACTION_FK1
    FOREIGN KEY (BLOCK_HEADER_REF)
    REFERENCES BTC_USER.BLOCK_HEADERS (BLOCK_HEADER_REF)
    ON DELETE CASCADE
    ENABLE
    VALIDATE
/
