DROP INDEX BTC_USER.OUTPUT_ADDRESSES_INDX1
/
CREATE INDEX BTC_USER.OUTPUT_ADDRESSES_INDX1
    ON BTC_USER.OUTPUT_ADDRESSES(TRANSACTION_OUTPUT_REF)
TABLESPACE USERS
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(INITIAL 64K
        BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
/
