CREATE TABLE BTC_USER.OUTPUT_ADDRESSES
(
    OUTPUT_ADDRESS_REF     NUMBER         NOT NULL,
    TRANSACTION_OUTPUT_REF NUMBER         NOT NULL,
    ADDRESS_INDEX          NUMBER         NOT NULL,
    PUBLIC_KEY             VARCHAR2(1024)     NULL,
    ADDRESS                VARCHAR2(64)       NULL,
    ADDRESS_TYPE           VARCHAR2(20)       NULL
)
ORGANIZATION HEAP
TABLESPACE USERS
LOGGING
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
NOROWDEPENDENCIES
/
ALTER TABLE BTC_USER.OUTPUT_ADDRESSES
    ADD CONSTRAINT OUTPUT_ADDRESSES_PK
    PRIMARY KEY (OUTPUT_ADDRESS_REF)
    USING INDEX TABLESPACE USERS
                PCTFREE 10
                INITRANS 2
                MAXTRANS 255
                STORAGE(BUFFER_POOL DEFAULT)
    LOGGING
    ENABLE
    VALIDATE
/
ALTER TABLE BTC_USER.OUTPUT_ADDRESSES
    ADD CONSTRAINT OUTPUT_ADDRESSES_FK1
    FOREIGN KEY (TRANSACTION_OUTPUT_REF)
    REFERENCES BTC_USER.TRANSACTION_OUTPUTS (TRANSACTION_OUTPUT_REF)
    ON DELETE CASCADE
    ENABLE
    VALIDATE
/
