DROP INDEX BTC_USER.TRANSACTION_INPUTS_INDX1
/
CREATE INDEX BTC_USER.TRANSACTION_INPUTS_INDX1
    ON BTC_USER.TRANSACTION_INPUTS(BLOCK_TRANSACTION_REF)
TABLESPACE USERS
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(INITIAL 64K
        BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
/
