DROP INDEX BTC_USER.UTXO_INDX2
/
CREATE BITMAP INDEX BTC_USER.UTXO_INDX2
    ON BTC_USER.UTXO(SPENT_FLAG)
TABLESPACE USERS
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(INITIAL 64K
        BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
/
