CREATE TABLE BTC_USER.UTXO_ADDRESSES
(
    TX_HASH       VARCHAR2(64)   NOT NULL,
    OUTPUT_INDEX  NUMBER(10,0)   NOT NULL,
    ADDRESS_INDEX NUMBER         NOT NULL,
    PUBLIC_KEY    VARCHAR2(1024)     NULL,
    ADDRESS       VARCHAR2(64)       NULL,
    ADDRESS_TYPE  VARCHAR2(20)       NULL
)
ORGANIZATION HEAP
TABLESPACE USERS
LOGGING
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
NOROWDEPENDENCIES
/
ALTER TABLE BTC_USER.UTXO_ADDRESSES
    ADD CONSTRAINT UTXO_ADDRESSES_PK
    PRIMARY KEY (TX_HASH,OUTPUT_INDEX)
    USING INDEX TABLESPACE USERS
                PCTFREE 10
                INITRANS 2
                MAXTRANS 255
                STORAGE(BUFFER_POOL DEFAULT)
    LOGGING
    ENABLE
    VALIDATE
/
ALTER TABLE BTC_USER.UTXO_ADDRESSES
    ADD CONSTRAINT UTXO_ADDRESSES_FK1
    FOREIGN KEY (TX_HASH,OUTPUT_INDEX)
    REFERENCES BTC_USER.UTXO (TX_HASH,OUTPUT_INDEX)
    ON DELETE CASCADE
    ENABLE
    VALIDATE
/
